name: Publish package
on:
  release:
    types: [ published ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v3

      - name: 'Download Java 14'
        run: wget -q https://download.java.net/java/GA/jdk14.0.2/205943a0976c4ed48cb16f1043c5c647/12/GPL/openjdk-14.0.2_linux-x64_bin.tar.gz

      - name: 'Setup Java'
        uses: actions/setup-java@v3
        with:
          distribution: 'jdkfile'
          jdkFile: ./openjdk-14.0.2_linux-x64_bin.tar.gz
          java-version: '14'
          architecture: 'x64'
          cache: 'maven'

      - name: 'Run Maven'
        run: mvn -B package

      - name: 'Setup environment variables for release'
        run: |
          ASSET=$(find target/ -name 'gcjfrlog*.jar')
          echo "ASSET=$ASSET" >> $GITHUB_ENV
        shell: bash

      - name: 'Upload Release Asset'
        uses: AButler/upload-release-assets@v2.0
        with:
          release-tag: ${{ github.ref_name }}
          files: ${{ env.ASSET }}
          repo-token: ${{ github.token }}
