name: Publish package
on:
  release:
    types: [ created ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v3

      - name: Setup Oracle OpenJDK 14
        uses: oracle-actions/setup-java@v1
        with:
          website: jdk.java.net
          release: 14

      - name: 'Run Maven'
        run: mvn -B package

      - name: 'Setup environment variables for release'
        run: |
          TAG=$(echo ${{ github.ref }} | cut -d '/' -f 3)
          ASSET=$(find target/ -name 'gcjfrlog*.jar')
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "ASSET=$ASSET" >> $GITHUB_ENV
        shell: bash

      - name: 'Upload Release Asset'
        uses: AButler/upload-release-assets@v2.0
        with:
          release-tag: ${{ env.TAG }}
          files: ${{ env.ASSET }}
          repo-token: ${{ github.token }}
